// Manuell kuratierte Redirects aus der GSC-Arbeitsliste (Nicole, 2026-08-06).
// Wird in next.config.ts VOR redirects.generated gespreadet — korrigiert dort
// u. a. 17 Eintraege, die bisher nur auf die Tool-UEBERSICHT zeigten.
// Quellen lowercase (Next matcht case-insensitiv); Gross-Varianten wie /Datenschutz
// loest der Root-Resolver per Lowercase-Redirect (Loop-Falle in redirects()!).
export const manualRedirects = [
  { source: "/abfindungsrechner", destination: "/finanztools/rechner/abfindung", permanent: true },
  { source: "/about", destination: "/impressum", permanent: true },
  { source: "/allianz-hausratversicherung", destination: "/allianz-versicherung-kontakt", permanent: true },
  { source: "/anbieter/versicherungen-kontakt", destination: "/anbieter", permanent: true },
  { source: "/anwaltskostenrechner", destination: "/finanztools/rechner/gerichtskosten", permanent: true },
  { source: "/arbeitslosengeldrechner", destination: "/finanztools/rechner/alg1", permanent: true },
  { source: "/barmenia-unfallversicherung-kuendigen", destination: "/barmenia-versicherung-kontakt", permanent: true },
  { source: "/basler-hausratversicherung", destination: "/basler-versicherung-kontakt", permanent: true },
  { source: "/betriebliche-riesterrente", destination: "/versicherungen/altersvorsorge/riester-rente", permanent: true },
  { source: "/bgv-haftpflichtversicherung", destination: "/bgv-versicherung-kontakt", permanent: true },
  { source: "/brutto-netto-gehaltsrechner", destination: "/finanztools/rechner/brutto-netto", permanent: true },
  { source: "/checkliste-laufende-kosten-eines-e-bikes", destination: "/finanztools/checklisten/e-bike-versicherung", permanent: true },
  { source: "/cosmos-direkt-unfallversicherung", destination: "/cosmos-direkt-versicherung-kontakt", permanent: true },
  { source: "/devk-hausratversicherung", destination: "/devk-versicherung-kontakt", permanent: true },
  { source: "/dienstunfaehigkeitsversicherung-beamte", destination: "/versicherungen/berufsunfaehigkeit", permanent: true },
  { source: "/dokumente-formulare", destination: "/dokumente", permanent: true },
  { source: "/ehegattenunterhaltrechner", destination: "/finanztools/rechner/unterhalt", permanent: true },
  { source: "/festgeld-rechner", destination: "/finanztools/vergleiche/festgeldvergleich", permanent: true },
  { source: "/finanzvergleich/versicherungsvergleich", destination: "/finanztools/vergleiche", permanent: true },
  { source: "/foerdermittel-neubau-und-sanierung", destination: "/finanzen/kredite-bauen/kfw-foerderung", permanent: true },
  { source: "/gebaeude-energie-gesetz-geg-2024", destination: "/finanzen/energiekosten", permanent: true },
  { source: "/gehaltsrechner", destination: "/finanztools/rechner/brutto-netto", permanent: true },
  { source: "/gehaltsrechner-2026.html", destination: "/finanztools/rechner/brutto-netto", permanent: true },
  { source: "/generali-versicherung-kontakt/%20hannover", destination: "/generali-versicherung-kontakt", permanent: true },
  { source: "/grundbuch", destination: "/finanzen/kredite-bauen", permanent: true },
  { source: "/grundrente", destination: "/dokumente/grundrente", permanent: true },
  { source: "/gvo-rechtsschutzversicherung", destination: "/gvo-versicherung-kontakt", permanent: true },
  { source: "/hausratversicherung-wechseln", destination: "/versicherungen/sachversicherungen/hausratversicherung", permanent: true },
  { source: "/hdi-haftpflichtversicherung", destination: "/hdi-versicherung-kontakt", permanent: true },
  { source: "/kfz-versicherung-rechner", destination: "/finanztools/vergleiche/kfz-versicherung-vergleich", permanent: true },
  { source: "/kindesunterhaltrechner", destination: "/finanztools/rechner/unterhalt", permanent: true },
  { source: "/krankengeld-rechner", destination: "/finanztools/rechner/krankengeld", permanent: true },
  { source: "/leasingrechner", destination: "/finanztools/rechner/leasing", permanent: true },
  { source: "/lebensversicherung-rechner", destination: "/finanztools/vergleiche/lebensversicherung-vergleich", permanent: true },
  { source: "/lohnsteuer-rechner", destination: "/finanztools/rechner/brutto-netto", permanent: true },
  { source: "/midijob", destination: "/finanztools/rechner/gleitzone", permanent: true },
  { source: "/mietkaution-rechner", destination: "/finanztools/vergleiche/mietkaution-rechner", permanent: true },
  { source: "/minijob-rechner", destination: "/finanztools/rechner/minijob", permanent: true },
  { source: "/mutterschaftsgeldrechner", destination: "/finanztools/rechner/mutterschutz", permanent: true },
  { source: "/newsletter", destination: "/", permanent: true },
  { source: "/notarkosten-grundbuchkosten", destination: "/finanzen/kredite-bauen", permanent: true },
  { source: "/ovag-versicherung", destination: "/anbieter", permanent: true },
  { source: "/pendlerpauschale-rechner", destination: "/finanztools/rechner/pendlerpauschale", permanent: true },
  { source: "/pensionsfonds", destination: "/versicherungen/altersvorsorge", permanent: true },
  { source: "/pensionskasse", destination: "/versicherungen/altersvorsorge", permanent: true },
  { source: "/pensionszusage", destination: "/versicherungen/altersvorsorge", permanent: true },
  { source: "/pflegetagegeld-vergleich", destination: "/versicherungen/pflegeversicherung", permanent: true },
  { source: "/private-krankenversicherung-rechner", destination: "/finanztools/vergleiche/private-krankenversicherung-vergleich", permanent: true },
  { source: "/prozesskostenrechner", destination: "/finanztools/rechner/gerichtskosten", permanent: true },
  { source: "/ratgeber/ratgeber-krankenversicherung", destination: "/versicherungen/krankenversicherung", permanent: true },
  { source: "/ratgeber/ratgeber-versicherungen/ratgeber-berufsunfaehigkeitsversicherung", destination: "/versicherungen/berufsunfaehigkeit", permanent: true },
  { source: "/ratgeber/ratgeber-versicherungen/ratgeber-tierversicherungen", destination: "/versicherungen/tierversicherungen", permanent: true },
  { source: "/rentenbesteuerungsrechner", destination: "/finanztools/rechner/rentenbesteuerung", permanent: true },
  { source: "/rentenlueckenrechner", destination: "/finanztools/vergleiche/rentenlueckenrechner", permanent: true },
  { source: "/ruv-versicherung-kuendigen", destination: "/anbieter", permanent: true },
  { source: "/steuererklaerung-frist", destination: "/steuern/steuerarten/steuererklaerung", permanent: true },
  { source: "/steuererstattung-steuererklaerung", destination: "/finanztools/rechner/steuererstattung", permanent: true },
  { source: "/steuerfreibetraege-pdf-2024", destination: "/dokumente", permanent: true },
  { source: "/steuern-deutschland", destination: "/steuern", permanent: true },
  { source: "/teilzeitrechner", destination: "/finanztools/rechner/teilzeit", permanent: true },
  { source: "/unterhaltsrechner", destination: "/finanztools/rechner/unterhalt", permanent: true },
  { source: "/versicherungen-vermieter-verwalter", destination: "/versicherungen/sachversicherungen", permanent: true },
  { source: "/versicherungskammer-bayern-haftpflichtversicherung-kuendigen", destination: "/versicherungskammer-bayern-versicherung-kontakt", permanent: true },
  { source: "/vhv-haftpflichtversicherung", destination: "/vhv-versicherung-kontakt", permanent: true },
  { source: "/wohnungsbaupraemie", destination: "/finanzen/kredite-bauen", permanent: true },
  { source: "/zinsrechner", destination: "/finanztools/rechner/zinseszins", permanent: true },
];
